import { supabase } from "@/integrations/supabase/client";
import { calculateNextReview } from "@/utils/review/fsrsUtils";

/**
 * Function to add an activity to the review system when completed in normal learning
 * This is called when a user completes an activity during the learning flow
 *
 * @param userId - The ID of the user
 * @param activityId - The ID of the activity that was completed
 * @param isCorrect - Whether the user answered correctly
 * @returns True if successful, false otherwise
 */
export const addActivityToReviewSystem = async (
	userId: string,
	activityId: string,
	isCorrect: boolean
): Promise<boolean> => {
	try {
		const now = new Date().toISOString();

		// Create initial FSRS state for a new activity
		const initialReviewState = calculateNextReview(
			{
				id: "", // Will be generated by database
				user_id: userId,
				activity_id: activityId,
				created_at: now,
				stability: null,
				difficulty: null,
				elapsed_days: null,
				scheduled_days: null,
				learning_steps: null,
				reps: null,
				lapses: null,
				state: "New",
				last_review: null, // New activities haven't been reviewed yet
				next_review: null,
			},
			isCorrect
		);

		const insertData = {
			user_id: userId,
			activity_id: activityId,
			created_at: now,
			...initialReviewState,
			last_review: initialReviewState.last_review.toISOString(),
			next_review: initialReviewState.next_review.toISOString(),
		};

		const { error: insertError } = await supabase
			.from("user_review_activities")
			.insert(insertData);

		if (insertError) {
			console.error("[addToReview] Error adding activity to review system:", insertError);
			return false;
		}

		console.log("[addToReview] Activity added to review system successfully");
		return true;
	} catch (error) {
		console.error("[addToReview] Error in addActivityToReviewSystem:", error);
		return false;
	}
};
