
export async function callOpenAI(openAIApiKey: string, systemPrompt: string, userPrompt: string, userProfile: any) {
  console.log('🤖 Preparing OpenAI API call...');
  console.log('📏 Prompt lengths:', {
    systemPrompt: systemPrompt.length,
    userPrompt: userPrompt.length,
    totalLength: systemPrompt.length + userPrompt.length,
    includesCountry: !!userProfile?.country
  });

  // Add timeout handling for OpenAI call
  console.log('🚀 Calling OpenAI API...');
  const startTime = Date.now();
  
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 30000); // 30 second timeout
  
  let response;
  try {
    response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openAIApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4.1-2025-04-14',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        temperature: 0.7,
        max_tokens: 800,
      }),
      signal: controller.signal,
    });
  } catch (error) {
    clearTimeout(timeoutId);
    if (error.name === 'AbortError') {
      console.error('❌ OpenAI API call timed out after 30 seconds');
      throw new Error('AI generation timed out. Please try again.');
    }
    throw error;
  }
  
  clearTimeout(timeoutId);

  const openAICallTime = Date.now() - startTime;
  console.log(`⏱️ OpenAI API call completed in ${openAICallTime}ms`);
  console.log('📊 OpenAI API response status:', response.status);
  console.log('✅ OpenAI API response ok:', response.ok);

  if (!response.ok) {
    const errorData = await response.text();
    console.error('❌ OpenAI API error:', {
      status: response.status,
      statusText: response.statusText,
      errorData: errorData.substring(0, 500)
    });
    throw new Error(`OpenAI API error: ${response.status} - ${errorData}`);
  }

  console.log('📥 Parsing OpenAI response...');
  const data = await response.json();
  console.log('✅ OpenAI response parsed:', {
    hasChoices: !!data.choices,
    choicesCount: data.choices?.length || 0,
    usage: data.usage
  });
  
  if (!data.choices || data.choices.length === 0) {
    console.error('❌ No choices in OpenAI response:', data);
    throw new Error('No response generated by OpenAI');
  }

  const aiResponse = data.choices[0].message.content;
  console.log('✅ AI response extracted:', {
    length: aiResponse?.length || 0,
    preview: aiResponse?.substring(0, 100) + '...'
  });

  if (!aiResponse) {
    console.error('❌ Empty AI response');
    throw new Error('Empty response from OpenAI');
  }

  return { aiResponse, openAICallTime };
}
