// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "../../types/supabase";

const SUPABASE_URL = "https://aeusujfuxnxwbvccmusk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
	"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFldXN1amZ1eG54d2J2Y2NtdXNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MDAwNDAsImV4cCI6MjA1NzQ3NjA0MH0.rMuOA4LyVVao4_alpNopj2E4mpzEHYxBOMJxv6jrOVA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
